### PR TITLE
Improve docs and binary handling

### PR DESCRIPTION
**Pull request by JasonLo**
**Summary of Changes:**
- Updated notebook organization: `user` folder for general users, `dev` folder for developers.
- Improved README documentation.
- Improved binary file handling.

@ilmcconnell I've made some changes to geolocation/macrostrat.py, please review. The main reason for this adjustment is that I encountered a write permission issue on HTCondor, where users cannot write directly to the installed Python package directory. This was disrupting the download process, so I've now included the macrostrat data as a binary file.

### CODE REVIEW

**Comment by JasonLo** [comment]
@iross  please review at readme

**Comment by ilmcconnell** [comment]
@JasonLo local binary for stratname records a good solution. Only caveat is assuming macrostrat doesn't change much ever - @iross true?

**Review by ilmcconnell — APPROVED** [review]
LGTM

**Review by iross — APPROVED** [review]
👍  looks good to me, too.

re: macrostrat stability, I don't think it changes at a high rate, so this looks like a good solution to me. If we wanted to make sure we're staying somewhat fresh, we could potentially add generation of that binary to the docker build step, but I don't feel it's necessary at this stage.

**Pull request merged**
