### PR TITLE
Ilm gkm conversion

### PR DESCRIPTION
**Pull request by ilmcconnell**
GKM conversion code.

The idea is to feed in a triplet and get the serialized GKM TTL back.

### CODE REVIEW

**Comment by ilmcconnell** [comment]
@JasonLo This is probably fine to merge for now as a v0.1 of the gkm conversion. Do you want to talk about adding this to an endpoint?

**Review by JasonLo — COMMENTED** [review]
so, I basically can just use get the ttl from ttl = graph_to_ttl_string(triplet_to_rdf(triplet))
and append it to the demo? It seems easy enough.

**Comment by JasonLo** [comment]
also, probably we want to close #7 ?

**Review by JasonLo — APPROVED** [review]
nice work

**Comment by ilmcconnell** [comment]
@JasonLo yes thats exactly it. I'll merge and close.

**Pull request merged**
